# Generated by Django 5.0.4 on 2024-04-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='homeImage',
        ),
    ]
