# Generated by Django 5.0.4 on 2024-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0004_designimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='designimages',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='designimages',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
