# Generated by Django 5.0.4 on 2024-04-18 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0007_designlabimages_studiesimages_toolsimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='aboutImages',
        ),
        migrations.DeleteModel(
            name='designImages',
        ),
        migrations.DeleteModel(
            name='designLabImages',
        ),
        migrations.DeleteModel(
            name='homeImage',
        ),
        migrations.DeleteModel(
            name='studiesImages',
        ),
        migrations.DeleteModel(
            name='toolsImages',
        ),
        migrations.DeleteModel(
            name='trainingImages',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FactWebApp.imagecategory'),
        ),
    ]
