# Generated by Django 5.0.4 on 2024-04-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0008_image_imagecategory_delete_aboutimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
