# Generated by Django 5.0.4 on 2024-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='role',
            field=models.CharField(default='Role', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(default='Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
