# Generated by Django 5.1.3 on 2024-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0014_team_image_remove_service_serviceimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team_image',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='this services is provided by Fact ltd, which is located in Kigali.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
