# Generated by Django 5.1.4 on 2024-12-10 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0015_delete_team_image_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
