# Generated by Django 5.1.3 on 2024-12-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0018_alter_service_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
