# Generated by Django 5.1.3 on 2024-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0019_rename_service_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='service_Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='service_title',
            field=models.CharField(default='Architectural and construction service', max_length=100),
        ),
    ]
