# Generated by Django 5.1.3 on 2024-12-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0020_image_service_description_image_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='magazine_type',
            field=models.CharField(default='Architectural magazine', max_length=100),
        ),
    ]
