# Generated by Django 5.1.3 on 2024-12-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0021_alter_image_magazine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='design_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_images', to='FactWebApp.imagecategory', verbose_name='Design Category'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(default='This service is provided by Fact Ltd, which is located in Kigali.'),
        ),
    ]
