# Generated by Django 5.1.3 on 2025-01-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactWebApp', '0023_remove_image_design_category_image_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='magazine_type',
            field=models.CharField(blank=True, default='Architectural magazine', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='role',
            field=models.CharField(blank=True, default='Role', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='service_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='service_title',
            field=models.CharField(blank=True, default='Architectural and construction service', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('residential-architecture', 'Residential Architecture'), ('single-family-homes', 'Single-family Homes'), ('multi-family-housing', 'Multi-family Housing (Apartments, Condominiums, etc.)'), ('villas-and-luxury-homes', 'Villas and Luxury Homes'), ('tiny-houses', 'Tiny Houses and Sustainable Housing'), ('commercial-architecture', 'Commercial Architecture'), ('office-buildings', 'Office Buildings'), ('retail-spaces', 'Retail Spaces (Shopping Malls, Storefronts, etc.)'), ('restaurants-and-cafes', 'Restaurants and Cafes'), ('mixed-use-developments', 'Mixed-use Developments'), ('industrial-architecture', 'Industrial Architecture'), ('factories', 'Factories'), ('warehouses', 'Warehouses'), ('power-plants', 'Power Plants'), ('data-centers', 'Data Centers'), ('institutional-architecture', 'Institutional Architecture'), ('schools-and-universities', 'Schools and Universities'), ('hospitals-and-healthcare', 'Hospitals and Healthcare Facilities'), ('libraries', 'Libraries'), ('museums-and-cultural-centers', 'Museums and Cultural Centers'), ('landscape-architecture', 'Landscape Architecture'), ('parks-and-recreational-areas', 'Parks and Recreational Areas'), ('urban-green-spaces', 'Urban Green Spaces'), ('gardens-and-terraces', 'Gardens and Terraces'), ('sustainable-landscapes', 'Sustainable Landscapes'), ('urban-planning', 'Urban Planning and Design'), ('city-planning', 'City Planning'), ('infrastructure-projects', 'Infrastructure Projects'), ('transportation-hubs', 'Transportation Hubs (Bus/Train Stations, Airports)'), ('zoning-and-land-use', 'Zoning and Land-use Planning'), ('interior-architecture', 'Interior Architecture and Design'), ('residential-interiors', 'Residential Interiors'), ('commercial-interiors', 'Commercial Interiors (Offices, Retail, etc.)'), ('hospitality-interiors', 'Hospitality Interiors (Hotels, Resorts, etc.)'), ('furniture-design', 'Furniture and Fixture Design'), ('sustainable-design', 'Sustainable and Green Design'), ('passive-solar-design', 'Passive Solar Design'), ('leed-certified-buildings', 'LEED-certified Buildings'), ('renewable-energy-integration', 'Renewable Energy Integration'), ('energy-efficient-buildings', 'Energy-efficient Buildings'), ('cultural-and-religious-architecture', 'Cultural and Religious Architecture'), ('religious-structures', 'Churches, Mosques, Temples, and Synagogues'), ('performing-arts-centers', 'Theaters and Performing Arts Centers'), ('heritage-preservation', 'Heritage and Preservation Projects'), ('specialized-architecture', 'Specialized Architecture'), ('sports-facilities', 'Sports Facilities and Stadiums'), ('convention-centers', 'Convention Centers'), ('amusement-parks', 'Amusement Parks'), ('aquariums-and-zoos', 'Aquariums and Zoos'), ('pre-construction', 'Pre-construction Design'), ('feasibility-studies', 'Feasibility Studies'), ('cost-estimation', 'Cost Estimation'), ('scheduling-and-planning', 'Scheduling and Planning'), ('risk-management', 'Risk Management Plans'), ('structural-design', 'Structural Design'), ('foundation-systems', 'Foundation Systems'), ('load-bearing-structures', 'Load-bearing Structures'), ('bridges-and-tunnels', 'Bridges and Tunnels'), ('high-rise-frameworks', 'High-rise Building Frameworks'), ('mep-design', 'Mechanical, Electrical, and Plumbing (MEP) Design'), ('hvac-systems', 'HVAC Systems'), ('plumbing-drainage-systems', 'Plumbing and Drainage Systems'), ('electrical-lighting-systems', 'Electrical Wiring and Lighting Systems'), ('fire-protection-systems', 'Fire Protection Systems'), ('civil-engineering-design', 'Civil Engineering Design'), ('road-highway-construction', 'Road and Highway Construction'), ('drainage-systems', 'Drainage Systems'), ('land-development', 'Land Development'), ('water-supply-systems', 'Water Supply Systems'), ('project-management', 'Project Management Design'), ('construction-logistics', 'Construction Logistics'), ('site-safety-plans', 'Site Safety Plans'), ('material-procurement-plans', 'Material Procurement Plans'), ('quality-control-measures', 'Quality Control Measures'), ('facade-roofing-design', 'Facade and Roofing Design'), ('curtain-wall-systems', 'Curtain Wall Systems'), ('energy-efficient-facades', 'Energy-efficient Facades'), ('green-roofs', 'Green Roofs'), ('skylights-atriums', 'Skylights and Atriums'), ('construction-technology', 'Construction Technology and Innovation'), ('bim', 'BIM (Building Information Modeling)'), ('prefabrication', 'Prefabrication and Modular Construction'), ('smart-building-systems', 'Smart Building Systems'), ('construction-robotics', 'Robotics and Automation in Construction'), ('sustainability-environmental-design', 'Sustainability and Environmental Design'), ('energy-efficient-materials', 'Energy-efficient Materials'), ('waste-management-strategies', 'Waste Management Strategies'), ('renewable-energy-construction', 'Renewable Energy Integration'), ('water-conservation-systems', 'Water Conservation Systems'), ('post-construction', 'Post-construction and Maintenance Design'), ('facility-management-systems', 'Facility Management Systems'), ('retrofitting-renovation', 'Retrofitting and Renovation'), ('maintenance-schedules', 'Maintenance Schedules'), ('asset-management', 'Asset Management'), ('disaster-resilient-design', 'Disaster-Resilient Design'), ('earthquake-resistant-buildings', 'Earthquake-resistant Buildings'), ('flood-protection-systems', 'Flood Protection Systems'), ('wind-resistant-designs', 'Wind and Hurricane-resistant Designs'), ('fire-safety-evacuation', 'Fire Safety and Evacuation Plans'), ('smart-city-design', 'Smart City Design'), ('iot-integration', 'IoT Integration'), ('digital-twin-modeling', 'Digital Twin Modeling'), ('smart-transportation-systems', 'Smart Transportation Systems'), ('heritage-conservation', 'Cultural Heritage and Conservation'), ('historic-building-restoration', 'Restoration of Historic Buildings'), ('adaptive-reuse', 'Adaptive Reuse of Old Structures'), ('healthcare-wellness-design', 'Healthcare and Wellness Design'), ('healing-environments', 'Healing Environments'), ('biophilic-design', 'Biophilic Design'), ('aging-in-place-housing', 'Aging-in-place Housing'), ('transportation-design', 'Transportation Design'), ('airports-seaports', 'Airports and Seaports'), ('bus-train-stations', 'Bus and Train Stations'), ('parking-structures', 'Parking Structures'), ('mixed-use-design', 'Mixed-use Development Design'), ('parametric-design', 'Parametric and Computational Design'), ('algorithm-driven-architecture', 'Algorithm-driven Architecture'), ('generative-design', 'Generative Design Processes')], default='others', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=100, null=True),
        ),
    ]
